import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import ModalProvider from "@/providers/modal-providers";
import ToastProvider from "@/providers/toast-providers";
import VoiceglowWidget from "@/components/voice-flow-widget";


const font = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecom Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ModalProvider />
        <ToastProvider />
        <Navbar />
        {children}
        <Footer />   
        <VoiceglowWidget />     
      </body>
    </html>
  );
}
